django_project_wind/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

#----ToDo: Check----
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('gewind.urls')),
    path('en/',include('gewind_en.urls')),

    # ----ToDo: Check----
    url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
]

# ----ToDo: Check----
# if settings.DEBUG: #added 10/06

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gewind/urls.py
from django.urls import path
from . import views

app_name='gewind'

urlpatterns=[
    path('about/', views.About.as_view(), name='about'),
    path('example/', views.UploadfileList.as_view(), name='example'),
    path('howto/', views.Howto.as_view(), name='howto'),
    path('', views.Top.as_view(), name='top'),
    path('make/', views.ProjectInfoFormsetView.as_view(), name='make'),
    path('make/dl/<str:slug>/',views.dl,name='dl'),

    # ----ToDo: Check----
    # path('test/thanks/<str:slug>/',views.Thanks.as_view(),name='thanks'),
    # ----ToDo: Check----
    # path('coordinatesinput/',views.index,name='coordinates_input'),
]

gewind_en/urls.py
from django.urls import path
from . import views

app_name='gewind_en'

urlpatterns=[
    path('about/', views.About.as_view(), name='about'),
    path('example/', views.Example.as_view(), name='example'),
    path('howto/', views.Howto.as_view(), name='howto'),
    path('', views.Top.as_view(), name='top'),
    path('make/', views.ProjectInfoFormsetView.as_view(), name='make'),
    path('make/dl/<str:slug>/',views.dl,name='dl'),

    # ----ToDo: Check----
    # path('test/thanks/<str:slug>/',views.Thanks.as_view(),name='thanks'),
    # ----ToDo: Check----
    # path('coordinatesinput/',views.index,name='coordinates_input'),
]

gewind/models.py
from django.db import models
import ulid

# Create your models here.

class Color(models.Model):
    color=models.CharField('色',max_length=255,unique=True)
    def __str__(self):
        return self.color

class ProjectInfo(models.Model):
    id=models.CharField(
        default=ulid.new,
        max_length=26,
        primary_key=True,
        editable=False
    )

    proj_id = models.CharField('プロジェクト名', max_length=255, unique=False,help_text='※Google Earth上に表示される名前です。')
    color = models.ForeignKey(Color, on_delete=models.PROTECT, verbose_name='風車の色',default=8)
    heading=models.IntegerField('風車の向き(0～360)',default=0,help_text='※数字は北（=0）から時計回り（参考：東=90, 南=180, 西=270）')
    hub_height=models.FloatField('ハブ高(m)',default=100)
    blade_length=models.FloatField('ブレードの長さ(m)',default=80,help_text='※値はローター直径ではなく、ローター半径です。')
    created_at=models.DateTimeField('作成日',auto_now_add=True)
    updated_at=models.DateTimeField('更新日',auto_now=True)
    appearance = models.BooleanField('ブレードの回転位置',help_text='※ブレードの回転位置をランダムにする場合はチェックを入れる。')
    paint_it_black = models.BooleanField('バードストライク対策', help_text='※ブレードの一部を黒くする場合はチェックを入れる。',default=False)#10/05

    def __str__(self):
        return self.proj_id

class Coordinates(models.Model):
    turbine_name=models.CharField('風車の名称',max_length=32,blank=True,help_text='a')
    lon=models.FloatField('経度',help_text='a',blank=False)
    lat = models.FloatField('緯度',help_text='a',blank=False)
    export_id = models.ForeignKey(ProjectInfo, on_delete=models.PROTECT, verbose_name='出力ID')

    def __str__(self):
        return self.turbine_name

class Uploadfile(models.Model):
    file = models.FileField('ファイル')
    name = models.CharField('ファイル名',max_length=32,blank=True)

    def __str__(self):
        return self.file.url

gewind/forms.py
from django import forms

class UploadFileForm(forms.Form):
    file = forms.FileField()

gewind/views.py
from .models import Coordinates,ProjectInfo
from extra_views import CreateWithInlinesView, InlineFormSet
from gewind.kmz_generator import main_run
from django.http import HttpResponse, HttpResponseNotFound
import mimetypes
from django.views import generic
from .models import Uploadfile

class About(generic.TemplateView):
    template_name= 'gewind/about.html'

class UploadfileList(generic.ListView):
    model = Uploadfile
    ordering = ['file']

class Top(generic.TemplateView):
    template_name= 'gewind/top.html'

class Howto(generic.TemplateView):
    template_name= 'gewind/howto.html'

class CoordinateFormView(InlineFormSet):
    model = Coordinates
    fields = ('turbine_name','lon','lat')
    factory_kwargs={'can_delete':False,'extra':10}

class ProjectInfoFormsetView(CreateWithInlinesView):
    model = ProjectInfo
    fields = ('proj_id', 'color', 'heading',
              'hub_height', 'blade_length','appearance','paint_it_black')
    inlines = [CoordinateFormView,]
    template_name = "gewind/projectinfo_formset.html"
    slug_field = 'id'
    success_url = "dl/{id}/"

def dl(request, slug):
    print(f'ProjectInfo id:{slug}')

    #-----Uncomment when the color has a problem
    # print(Color.objects.all().values())
    #-----

    proj_info_dic = ProjectInfo.objects.all().values().filter(id=slug)
    pro_id_id=proj_info_dic[0]['id']

    proj_id = proj_info_dic[0]['proj_id']
    coor_info_dic = Coordinates.objects.all().values().filter(export_id=pro_id_id)

    #----- Uncomment when the input data has a problem
    # print(proj_info_dic)
    # print(coor_info_dic )
    #-----

    color = proj_info_dic[0]['color_id']
    heading = proj_info_dic[0]['heading']
    random_rotation = proj_info_dic[0]['appearance']
    paint_it_black = proj_info_dic[0]['paint_it_black']#10/05
    hub_height = proj_info_dic[0]['hub_height']
    roter_radius_input = proj_info_dic[0]['blade_length']

    lon_ls = []
    lat_ls = []
    turbine_num_ls = []

    for dic in coor_info_dic:
        if dic['turbine_name']=="":
            turbine_num_ls.append("風車")
        else:
            turbine_num_ls.append(dic['turbine_name'])

        lon_ls.append(dic['lon'])
        lat_ls.append(dic['lat'])

    main_run.main_run_all(roter_radius_input,lon_ls,lat_ls,hub_height,heading,random_rotation,color,turbine_num_ls,slug,proj_id,paint_it_black)#10/05

    fl_path = './tmp/' #Heroku対応
    filename = f'output_{slug}.kmz'
    file_location = f'{fl_path}{filename}'

    try:
        '''
        Use 'rb' instead of 'r' for open()
        Source: https://stackoverflow.com/questions/19459300/how-to-serve-downloadable-zip-file-in-django
        '''
        kmz_file = open(file_location, 'rb')
        mime_type, _ = mimetypes.guess_type(file_location) #mime_type is application/vnd.google-earth.kmz
        response = HttpResponse(kmz_file, content_type=mime_type)
        response['Content-Disposition'] = 'attachment; filename="%s"' % filename
        return response

    except IOError:
        # handle file not exist case here
        response = HttpResponseNotFound('<h1>File not exist</h1>')

    return response

#----ToDo: Check----
# def download(request,path):
#     file_path=os.path.join(settings.MEDIA_ROOT,path)
#     print('!!!!')
#     print(file_path)
#     print('!!!!')
#     if os.path.exists(file_path):
#         with open(file_path,'rb')as fh:
#             response=HttpResponse(fh.read(),content_type="application/file")
#             response['Content-Disposition']='inline;filename='+os.path.basename(file_path)
#             return response
#     raise Http404


#----ToDo: Check----
# class Thanks(generic.TemplateView):
#     model = ProjectInfo
#     slug_field = 'proj_id'
#     extra_context = {'proj_id': '<str:slug>'}
#     template_name='gewind/thanks.html'

#----ToDo: Check----
# def index(request):
#     ExampleFormSet=modelformset_factory(Coordinates,
#                                         fields=('turbine_name','lon','lat','proj_id'),
#                                         extra=10)
#     if request.method=='POST':
#         form = ExampleFormSet(request.POST)
#         instances = form.save(commit=False)
#         for instance in instances:
#             instance.save()
#     # querysetによって表示するデータの種類をコントロールする。
#     form = ExampleFormSet(queryset=Coordinates.objects.none())
#     return render(request,'gewind/coordinates_form.html',{'form':form})

#----ToDo: Check----
# def upload_file(request):
#     if request.method == 'POST':
#         form = UploadFileForm(request.POST)#, request.FILES)
#         if form.is_valid():
#             instance = Uploadfile(file_field=request.FILES['file'])
#             instance.save()
#             return HttpResponseRedirect('/success/url/')
#     else:
#         form = UploadFileForm()
#     return render(request, 'upload.html', {'form': form})


gewind/templates/gewind/about.html
{% extends 'gewind/base.html' %}

{% block title %}管理人{% endblock %}

{% block content %}

<h1>管理人</h1>
    <br>
    <p>新卒で入社した会社では環境系の仕事をしていました。備忘録代わりに<a href="https://tropicbird.hatenablog.com/">ブログ</a>も書いています。<br>
        WebアプリのソースコードはGitHubにて公開予定です。現在コードを整理・整形中です。<br>
        </p>

{% endblock %}

gewind/templates/gewind/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  {% if GOOGLE_ANALYTICS_TRACKING_ID %}
    {% include 'gewind/ga.html' %}
  {% endif %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<br>
<p><a href="{% url 'gewind:top' %}">日本語</a> | <a href="{% url 'gewind_en:top' %}">English</a></p>
<header>Google Earth上に風車をつくるWebアプリ</header>
<nav>
    <a href="{% url 'gewind:top' %}">トップ</a>
    <a href="{% url 'gewind:howto' %}">使い方</a>
    <a href="{% url 'gewind:make' %}">風車をつくる</a>
    <a href="{% url 'gewind:example' %}">サンプル</a>
    <a href="{% url 'gewind:about' %}">管理人</a>

</nav>

<style>
        *{
            margin: 0;
        }

        body{
            color:#333;
            max-width: 900px;
            margin: 0 auto;
            padding-left: 40px;
            padding-right: 40px;
        }

        body > header{
            color:#999;
            font-size:36px;
            margin-top: 25px;
            margin-bottom: 25px;
            text-align: center;
        }

        body > nav {
            {#color:#999;#}
            font-size:20px;
            {#margin-top: 50px;#}
            margin-bottom: 25px;
            text-align: center;
        }

        body > nav > a{
            padding-left: 40px;
            padding-right: 40px;
        }

        div.sample1 {

        display: inline-block;

        text-align: center;
            width:1000px;

        }

        div.field {

        display: inline-block;

        text-align: center;

        width: 1000px;

        }

        div.col-1 {
            display: inline-block;
            width: 200px;
            text-align: right;
            /* border: solid 1px; */
        }
        div.col-2 {
            display: inline-block;
            width: 180px;
            text-align: left;
            /* border: solid 1px; */
        }
        div.col-3 {
            display: inline-block;
            width: 550px;
            text-align: left;
            /* border: solid 1px; */
        }
        div.col-4 {
            display: inline-block;
            text-align: left;
            margin-block-end: 10px;
            margin-block: 10px;
            /* border: solid 1px; */
        }

        div.col-5 {
            display: inline-block;
            text-align: left;
            margin-block-end: 10px;
            margin-block: 10px;
            margin-right: 10px;
            /* border: solid 1px; */
        }

        div.button_wrapper{
            text-align:center;
}
        #kmzinfo {
            font-size: 30px;
            padding: 10px;
        }


        img{
            width:100%;
            height:auto;
            margin-left: auto;
            margin-right: auto;
        }

        img.topimg{
            display: block;
            width: 60%;
        }
    </style>

<hr>
<br>
{% block content %}{% endblock %}

</body>
</html>

gewind/templates/gewind/howto.html
{% extends 'gewind/base.html' %}

{% block title %}使い方{% endblock %}

{% block content %}

    <h1>使い方（動画：3分28秒）</h1>
    <br>
    <p align="center">
<iframe width="900" height="600" src="https://www.youtube.com/embed/IwsiNnZNRjk" frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
</p>
{% endblock %}

gewind/templates/gewind/projectinfo_formset.html
{% extends "gewind/base.html" %}

{% block title %}風車をつくる{% endblock %}

{% block content %}
    {{ inlines.as_table }}
    {{ inlines.management_form }}

    <script type="text/javascript">
    <!--
    function check(){
        if(window.confirm('入力された内容でダウンロードファイルを作成しますか？（※時間帯によっては出力に10秒以上かかる場合もあります。）')){ // 確認ダイアログを表示
            return true; // 「OK」時は送信を実行
        }
        else{ // 「キャンセル」時の処理
            window.alert('キャンセルされました'); // 警告ダイアログを表示
            return false; // 送信を中止
        }
    }
    // -->
    </script>

    <form method="post" onSubmit="return check()">
        {% csrf_token %}

        <table>
                <h1 align="left">ステップ1. 風車のスペックを入力</h1>
            <p>風車のスペックを以下のフォームに入力してください。出力される風車の支柱の直径は4 m、ナセルの大きさは4 m &times; 4 m &times; 12 mです。</p>
            <br>
<div>
    <div>
        <div class="sample1">
        {% for field in form %}
        <div style="float:left;">
             <div class="col-1">
                 <b>{{ field.label_tag }}</b>
            </div>
            <div class="col-2">
            {{ field }}
            </div>
            <div class="col-3">
            {{ field.help_text }}
            </div>
            <br>
        {% endfor %}
            </div>
        </div>
    </div>
</div>
        </table>
    <p align="right">
        （バードストライク対策参考文献：
        <a href="https://onlinelibrary.wiley.com/doi/10.1002/ece3.6592">May et al. (2020)</a>、
        <a href="https://www.bbc.com/news/science-environment-53909825">BBC (2020)</a>）
    </p>
　　　　　　　　　　　　　　　 {# インラインはinlinesという変数にリストで入っている #}
        <h1 align="left">ステップ2. 風車の座標を入力</h1>
    <p>任意の数（最大10基）の風車の座標を10進表記（例：134.43233）で入力してください。
        <a href="https://tomari.org/main/java/do_henkan.html">こちらのサイト</a>等で
        60進表記（例：東経134度25分56秒）を10進表記に変換できます。
        「風車の名称」は空欄可ですが、例えば「1号基」などと入力しておけば、Googe Earth上の表示が分かりやすくなります。
        </p>

    <br>
    <div>
    <div class="sample1">
        <table>
            {% for formset in inlines %}
                {# formset.management_form　は必須 #}
                {{ formset.management_form }}

                {% for form in formset %}
                    {% for field in form %}
                        {# field.errors　は必須 #}
                        {{ field.errors }}
                        {% if field.help_text %}

                        <div class="col-4">
                            <b>{{ field.label_tag }}</b>
                        </div>
                        <div class="col-5">
                        {{ field }}
                        </div>
                        {% endif %}
                        {% endfor %}
                    <br>
                {% endfor %}
            {% endfor %}
        </table>

    </div>
        <div class="button_wrapper">
        <button type="submit" id="kmzinfo" >ステップ3. 風車モデル（.kmz）を出力</button>
    </div>
    </div>
    </div>
    </form>

{% endblock %}

gewind/templates/gewind/top.html
{% extends 'gewind/base.html' %}
{% load static %}

{% block title %}トップ{% endblock %}

{% block content %}



    <h1>はじめに</h1>
    <p><img src="{% static "gewind/sample1.jpg" %}" class="topimg"></p>
    <br>
    <p>
    このサイトはGoogle Earth（グーグルアース）上で開ける風車の3Dモデルを生成する無料のWebアプリです。
        デスクトップ版Google Earthで開けるKMZファイルを出力します。お使いのPCにまだGoogle Earthをインストールされていない方は
        <a href="https://www.google.com/earth/versions/#download-pro">こちらからダウンロードができます。</a>
    </p>
        <br>
    一応、このWebアプリの使い道として以下の2点を想定していますが、適宜お好きな用途にお使いください。<br><br>
        <ul>
            <li>風力発電施設の建設前後におけるイメージの共有、検討</li>
            <li>環境アセスメントにおける景観への影響の簡易予測</li>
        </ul>
    <br>



    本サイトに関するお問い合わせや、機能に関する要望がありましたら
    <a href="mailto:tropicbird38@gmail.com">tropicbird38@gmail.com</a>までご連絡ください。<br>
    <br>
    <p align="right">（更新日：2020年10月9日）</p>

{% endblock %}

gewind/templates/gewind/uploadfile_list.html
{% extends 'gewind/base.html' %}
{% load static %}

{% block title %}サンプル{% endblock %}

{% block content %}

    <h1>サンプルファイル</h1>
{#    {% for uploadfile in uploadfile_list %}#}
{#        <br>#}
{#        <a href="{{ uploadfile.file.url }}"> {{ uploadfile.file}} </a>#}
{##}
{#    {% endfor %}#}
{#    (※バードストライク対策のオプションにチェックを入れた場合)#}
{#    <br>#}
{#    <br>#}

    <h3><a href="https://www.dropbox.com/s/5y8sqia9ncnclj4/sample1.kmz?dl=1">sample1.kmz</a></h3>
    <p><img src="{% static "gewind/sample1.jpg" %}"></p>
    <br>
    <h3><a href="https://www.dropbox.com/s/hatndm4gfygizuo/sample2.kmz?dl=1">sample2.kmz</a></h3>
    <p><img src="{% static "gewind/sample2.jpg" %}"></p>
    <br>
    <h3><a href="https://www.dropbox.com/s/6sx24evoaag9yo5/sample3.kmz?dl=1">sample3.kmz</a></h3>
    <p><img src="{% static "gewind/sample3.jpg" %}"></p>
    <br>
    <h3><a href="https://www.dropbox.com/s/4co9fsa4ppofib5/sample4.kmz?dl=1">sample4.kmz</a></h3>
    <p><img src="{% static "gewind/sample4.jpg" %}"></p>
    <br>
    <h3><a href="https://www.dropbox.com/s/ms5iplejxg7f7z4/sample5.kmz?dl=1">sample5.kmz</a>(※バードストライク対策のオプションにチェックを入れた場合)</h3>
    <p><img src="{% static "gewind/sample5.jpg" %}"></p>
{% endblock %}