django_project_wind/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

#----ToDo: Check----
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('gewind.urls')),
    path('en/',include('gewind_en.urls')),

    # ----ToDo: Check----
    url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
]

# ----ToDo: Check----
# if settings.DEBUG: #added 10/06

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gewind/urls.py
from django.urls import path
from . import views

app_name='gewind'

urlpatterns=[
    path('about/', views.About.as_view(), name='about'),
    path('example/', views.UploadfileList.as_view(), name='example'),
    path('howto/', views.Howto.as_view(), name='howto'),
    path('', views.Top.as_view(), name='top'),
    path('make/', views.ProjectInfoFormsetView.as_view(), name='make'),
    path('make/dl/<str:slug>/',views.dl,name='dl'),

    # ----ToDo: Check----
    # path('test/thanks/<str:slug>/',views.Thanks.as_view(),name='thanks'),
    # ----ToDo: Check----
    # path('coordinatesinput/',views.index,name='coordinates_input'),
]

gewind_en/urls.py
from django.urls import path
from . import views

app_name='gewind_en'

urlpatterns=[
    path('about/', views.About.as_view(), name='about'),
    path('example/', views.Example.as_view(), name='example'),
    path('howto/', views.Howto.as_view(), name='howto'),
    path('', views.Top.as_view(), name='top'),
    path('make/', views.ProjectInfoFormsetView.as_view(), name='make'),
    path('make/dl/<str:slug>/',views.dl,name='dl'),

    # ----ToDo: Check----
    # path('test/thanks/<str:slug>/',views.Thanks.as_view(),name='thanks'),
    # ----ToDo: Check----
    # path('coordinatesinput/',views.index,name='coordinates_input'),
]

gewind_en/models.py
from django.db import models
import ulid

# Create your models here.

class Color(models.Model):
    color=models.CharField('Color',max_length=255,unique=True)
    def __str__(self):
        return self.color

class ProjectInfo(models.Model):
    id=models.CharField(
        default=ulid.new,
        max_length=26,
        primary_key=True,
        editable=False
    )

    proj_id = models.CharField('Project Name', max_length=255, unique=False)
    color = models.ForeignKey(Color, on_delete=models.PROTECT, verbose_name='Color',default=8)
    heading=models.IntegerField('Heading (0 to 360)',default=0,help_text='*North = 0, East = 90, South = 180, West = 270')
    hub_height=models.FloatField('Hub height (m)',default=100)
    blade_length=models.FloatField('Blade length (m)',default=80,help_text='*It is a rotor radius, NOT a rotor diameter.')
    created_at=models.DateTimeField('Created',auto_now_add=True)
    updated_at=models.DateTimeField('Updated',auto_now=True)
    appearance = models.BooleanField('Position of the blade',help_text='*Check the box if you want the blade rotation position to be random.')
    paint_it_black = models.BooleanField('Birdstrike prevention', help_text='*Check the box if you want part of the blade to be black.', default=False)  # 10/05

    def __str__(self):
        return self.proj_id

class Coordinates(models.Model):
    turbine_name=models.CharField('Wind turbine name',max_length=32,blank=True,help_text='a')
    lon=models.FloatField('Longitude',help_text='a',blank=False)
    lat = models.FloatField('Latitude',help_text='a',blank=False)
    export_id = models.ForeignKey(ProjectInfo, on_delete=models.PROTECT, verbose_name='export_id')

    def __str__(self):
        return self.turbine_name

class Uploadfile(models.Model):
    file = models.FileField('File')
    name = models.CharField('Name of the file',max_length=32,blank=True)

    def __str__(self):
        return self.file.url

gewind_en/forms.py
from django import forms

class UploadFileForm(forms.Form):
    file = forms.FileField()

gewind_en/views.py
from .models import Coordinates,ProjectInfo,Color, Uploadfile
from extra_views import CreateWithInlinesView, InlineFormSet
from gewind_en.kmz_generator import main_run
from django.http import HttpResponse, HttpResponseNotFound
import mimetypes
from django.views import generic
from .models import Uploadfile

class About(generic.TemplateView):
    template_name= 'gewind_en/about.html'

class Example(generic.ListView):
    model = Uploadfile
    ordering = ['file']

class Top(generic.TemplateView):
    template_name= 'gewind_en/top.html'

class Howto(generic.TemplateView):
    template_name= 'gewind_en/howto.html'

class CoordinateFormView(InlineFormSet):
    model = Coordinates
    fields = ('turbine_name','lon','lat')
    factory_kwargs={'can_delete':False,'extra':10}

class ProjectInfoFormsetView(CreateWithInlinesView):
    model = ProjectInfo
    fields = ('proj_id', 'color', 'heading',
              'hub_height', 'blade_length','appearance','paint_it_black')
    inlines = [CoordinateFormView,]
    template_name = "gewind_en/projectinfo_formset.html"
    slug_field = 'id'
    success_url = "dl/{id}/"

def dl(request, slug):
    print(f'ProjectInfo id:{slug}')

    #-----Uncomment when the color has a problem
    # print(Color.objects.all().values())
    #-----

    proj_info_dic = ProjectInfo.objects.all().values().filter(id=slug)
    pro_id_id=proj_info_dic[0]['id']

    proj_id = proj_info_dic[0]['proj_id']
    coor_info_dic = Coordinates.objects.all().values().filter(export_id=pro_id_id)

    #----- Uncomment when the input data has a problem
    # print(proj_info_dic)
    # print(coor_info_dic )
    #-----

    color = proj_info_dic[0]['color_id']
    heading = proj_info_dic[0]['heading']
    random_rotation = proj_info_dic[0]['appearance']
    paint_it_black = proj_info_dic[0]['paint_it_black']  # 10/05
    hub_height = proj_info_dic[0]['hub_height']
    roter_radius_input = proj_info_dic[0]['blade_length']

    lon_ls = []
    lat_ls = []
    turbine_num_ls = []

    for dic in coor_info_dic:
        if dic['turbine_name']=="":
            turbine_num_ls.append("WT")
        else:
            turbine_num_ls.append(dic['turbine_name'])

        lon_ls.append(dic['lon'])
        lat_ls.append(dic['lat'])

    main_run.main_run_all(roter_radius_input,lon_ls,lat_ls,hub_height,heading,random_rotation,color,turbine_num_ls,slug,proj_id,paint_it_black)#10/05

    fl_path = './tmp/' #Heroku対応
    filename = f'output_{slug}.kmz'
    file_location = f'{fl_path}{filename}'

    try:
        '''
        Use 'rb' instead of 'r' for open()
        Source: https://stackoverflow.com/questions/19459300/how-to-serve-downloadable-zip-file-in-django
        '''
        kmz_file = open(file_location, 'rb')
        mime_type, _ = mimetypes.guess_type(file_location) #mime_type is application/vnd.google-earth.kmz
        response = HttpResponse(kmz_file, content_type=mime_type)
        response['Content-Disposition'] = 'attachment; filename="%s"' % filename
        return response

    except IOError:
        # handle file not exist case here
        response = HttpResponseNotFound('<h1>File not exist</h1>')

    return response

#----ToDo: Check----
# def download(request,path):
#     file_path=os.path.join(settings.MEDIA_ROOT,path)
#     print('!!!!')
#     print(file_path)
#     print('!!!!')
#     if os.path.exists(file_path):
#         with open(file_path,'rb')as fh:
#             response=HttpResponse(fh.read(),content_type="application/file")
#             response['Content-Disposition']='inline;filename='+os.path.basename(file_path)
#             return response
#     raise Http404


#----ToDo: Check----
# class Thanks(generic.TemplateView):
#     model = ProjectInfo
#     slug_field = 'proj_id'
#     extra_context = {'proj_id': '<str:slug>'}
#     template_name='gewind_en/thanks.html'

#----ToDo: Check----
# def index(request):
#     ExampleFormSet=modelformset_factory(Coordinates,
#                                         fields=('turbine_name','lon','lat','proj_id'),
#                                         extra=10)
#     if request.method=='POST':
#         form = ExampleFormSet(request.POST)
#         instances = form.save(commit=False)
#         for instance in instances:
#             instance.save()
#     # querysetによって表示するデータの種類をコントロールする。
#     form = ExampleFormSet(queryset=Coordinates.objects.none())
#     return render(request,'gewind_en/coordinates_form.html',{'form':form})

#----ToDo: Check----
# def upload_file(request):
#     if request.method == 'POST':
#         form = UploadFileForm(request.POST)#, request.FILES)
#         if form.is_valid():
#             instance = Uploadfile(file_field=request.FILES['file'])
#             instance.save()
#             return HttpResponseRedirect('/success/url/')
#     else:
#         form = UploadFileForm()
#     return render(request, 'upload.html', {'form': form})


gewind_en/templates/gewind_en/about.html
{% extends 'gewind_en/base.html' %}

{% block title %}About{% endblock %}

{% block content %}

<h1>Who is managing this website?</h1>
    <br>
    <p>Hello! Thank you for using this web app.
        Regarding my background, I was working as an environmental consultant,
        especially about Environmental Impact Assessment,
        at a company in Japan for a couple of years.
        <br>
        <br>

        I made this app as my hobby when I was self-studying Django framework.
        I hope you will find this web app useful for your purpose.
        I am going to share the code of this web app through the GitHub soon :) !
        <br>
        <br>

        Link: <a href="https://tropicbird.hatenablog.com/">my blog</a> (in Japanese)<br>
        </p>

{% endblock %}

gewind_en/templates/gewind_en/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  {% if GOOGLE_ANALYTICS_TRACKING_ID %}
    {% include 'gewind/ga.html' %}
  {% endif %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<br>
<p><a href="{% url 'gewind:top' %}">日本語</a> | <a href="{% url 'gewind_en:top' %}">English</a></p>
<header>Web App to Create Wind Farm on Google Earth</header>
<nav>
    <a href="{% url 'gewind_en:top' %}">Top</a>
    <a href="{% url 'gewind_en:howto' %}">Instructions</a>
    <a href="{% url 'gewind_en:make' %}">Create</a>
    <a href="{% url 'gewind_en:example' %}">Samples</a>
    <a href="{% url 'gewind_en:about' %}">About</a>

</nav>

<style>
        *{
            margin: 0;
        }

        body{
            color:#333;
            max-width: 900px;
            margin: 0 auto;
            padding-left: 40px;
            padding-right: 40px;
        }

        body > header{
            color:#999;
            font-size:36px;
            margin-top: 25px;
            margin-bottom: 25px;
            text-align: center;
        }

        body > nav {
            {#color:#999;#}
            font-size:20px;
            {#margin-top: 50px;#}
            margin-bottom: 25px;
            text-align: center;
        }

        body > nav > a{
            padding-left: 40px;
            padding-right: 40px;
        }

        div.sample1 {

        display: inline-block;

        text-align: center;
            width:1000px;

        }

        div.field {

        display: inline-block;

        text-align: center;

        width: 1000px;

        }

        div.col-1 {
            display: inline-block;
            width: 200px;
            text-align: right;
            /* border: solid 1px; */
        }
        div.col-2 {
            display: inline-block;
            width: 180px;
            text-align: left;
            /* border: solid 1px; */
        }
        div.col-3 {
            display: inline-block;
            width: 550px;
            text-align: left;
            /* border: solid 1px; */
        }
        div.col-4 {
            display: inline-block;
            text-align: left;
            margin-block-end: 10px;
            margin-block: 10px;
            /* border: solid 1px; */
        }

        div.col-5 {
            display: inline-block;
            text-align: left;
            margin-block-end: 10px;
            margin-block: 10px;
            margin-right: 10px;
            /* border: solid 1px; */
        }

        div.button_wrapper{
            text-align:center;
}
        #kmzinfo {
            font-size: 30px;
            padding: 10px;
        }

        img{
            width:100%;
            height:auto;
            margin-left: auto;
            margin-right: auto;
        }

        img.topimg{
            display: block;
            width: 60%;
        }
    </style>

<hr>
<br>
{% block content %}{% endblock %}

</body>
</html>

gewind_en/templates/gewind_en/howto.html
{% extends 'gewind_en/base.html' %}

{% block title %}Instructions{% endblock %}

{% block content %}

    <h1>How to Use (Video: 3 min 33 sec)</h1>
    <br>
    <p align="center">
<iframe width="900" height="600" src="https://www.youtube.com/embed/hMjDYvm7bEI" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</p>
{% endblock %}

gewind_en/templates/gewind_en/projectinfo_formset.html
{% extends "gewind_en/base.html" %}

{% block title %}Create{% endblock %}

{% block content %}
    {{ inlines.as_table }}
    {{ inlines.management_form }}

    <script type="text/javascript">
    <!--
    function check(){
        if(window.confirm('Do you proceed to create a downloadable file with the information you\'ve entered? ')){ // 確認ダイアログを表示
            return true; // 「OK」時は送信を実行
        }
        else{ // 「キャンセル」時の処理
            window.alert('The process is canceled.'); // 警告ダイアログを表示
            return false; // 送信を中止
        }
    }
    // -->
    </script>

    <form method="post" onSubmit="return check()">
        {% csrf_token %}

        <table>
                <h1 align="left">Step 1. Input the general information</h1>
            <p>Please input the specification of the wind turbines you want to create in the form below.
                Regarding the 3D model of the wind turbine in this app, the diameter of the tower is set to 4 meters,
                and the size of the nacelle is set to 4 meter &times; 4 meter &times; 12 meter.</p>
            <br>
<div>
    <div>
        <div class="sample1">
        {% for field in form %}
        <div style="float:left;">
             <div class="col-1">
                 <b>{{ field.label_tag }}</b>
            </div>
            <div class="col-2">
            {{ field }}
            </div>
            <div class="col-3">
            {{ field.help_text }}
            </div>
            <br>
        {% endfor %}
            </div>
        </div>
    </div>
</div>
        </table>
    <p align="right">
        (Reference for the birdstrike prevention:
        <a href="https://onlinelibrary.wiley.com/doi/10.1002/ece3.6592">May et al. (2020)</a>,
        <a href="https://www.bbc.com/news/science-environment-53909825">BBC (2020)</a>)
    </p>

　　　　　　　　　　　　　　　 {# インラインはinlinesという変数にリストで入っている #}
        <h1 align="left">Step 2. Input the coordinates of the wind turbines</h1>
    <p>Please enter the coordinates of any number of wind turbines (up to 10) in decimal format (e.g. 134.43233).
        If your coordinates are other format such as 60-decimal notation (e.g. 134 degrees 25 minutes 56 seconds),
        please convert the format to decimal format first. You can leave the "Wind turbine name" field blank,
        but if you type in, for example, "WT1", it will be easier for you to recognize the wind turbine on Googe Earth.
        </p>




    <br>
    <div>
    <div class="sample1">
        <table>
            {% for formset in inlines %}
                {# formset.management_form　は必須 #}
                {{ formset.management_form }}

                {% for form in formset %}
                    {% for field in form %}
                        {# field.errors　は必須 #}
                        {{ field.errors }}
                        {% if field.help_text %}

                        <div class="col-4">
                            <b>{{ field.label_tag }}</b>
                        </div>
                        <div class="col-5">
                        {{ field }}
                        </div>
                        {% endif %}
                        {% endfor %}
                    <br>
                {% endfor %}
            {% endfor %}
        </table>

    </div>
        <div class="button_wrapper">
        <button type="submit" id="kmzinfo" >Step 3. Generate the wind turbines (i.e. kmz file)</button>
    </div>
    </div>
    </div>
    </form>

{% endblock %}

gewind_en/templates/gewind_en/top.html
{% extends 'gewind_en/base.html' %}
{% load static %}

{% block title %}Top{% endblock %}

{% block content %}

    <h1>Welcome!</h1>
    <p><img src="{% static "gewind_en/sample1.jpg" %}" class="topimg"></p>
    <br>
    <p>
    This site is a free web app that generates a 3D model of wind turbines that you can open on Google Earth.
        The file format is KMZ, so that you can open with the desktop version of Google Earth.
        If you don't have the desktop version of Google Earth installed on your PC yet, you can download it from
        <a href="https://www.google.com/earth/versions/#download-pro">here</a>.
    </p>
        <br>

    You can use this web app in any way you like, but we designed this web app for the following two applications.<br><br>
        <ul>
            <li>To share and review a wind farm project with its stakeholders before and after the construction</li>
            <li>To make a simple prediction of the impacts of a wind farm project on landscape in Environmental Impact Assessment</li>
        </ul>
    <br>


    If you have any questions about this site or requests for features of this web app, please contact me via
    <a href="mailto:tropicbird38@gmail.com">tropicbird38@gmail.com</a>.<br>
    <br>
    <p align="right">(Updated: 10/09/2020)</p>

{% endblock %}

gewind_en/templates/gewind_en/uploadfile_list.html
{% extends 'gewind_en/base.html' %}
{% load static %}

{% block title %}Samples{% endblock %}

{% block content %}

    <h1>Sample files</h1>
{#    {% for uploadfile in object_list %}#}
{#        <br>#}
{#        <a href="{{ uploadfile.file.url }}"> {{ uploadfile.file }} </a>#}
{#    {% endfor %}#}
{#    (*birdstrike prevention version)#}
{#    <br>#}
{#    <br>#}

    <h3><a href="https://www.dropbox.com/s/vmzenaofqjso3en/sample1_en.kmz?dl=1">sample1_en.kmz</a></h3>
    <p><img src="{% static "gewind_en/sample1.jpg" %}"></p>
    <br>
    <h3><a href="https://www.dropbox.com/s/g49dq7gegnwlz5z/sample2_en.kmz?dl=1">sample2_en.kmz</a></h3>
    <p><img src="{% static "gewind_en/sample2.jpg" %}"></p>
    <br>
    <h3><a href="https://www.dropbox.com/s/0aios1pk4xdnv4d/sample3_en.kmz?dl=1">sample3_en.kmz</a></h3>
    <p><img src="{% static "gewind_en/sample3.jpg" %}"></p>
    <br>
    <h3><a href="https://www.dropbox.com/s/5crwczssa6cv7ie/sample4_en.kmz?dl=1">sample4_en.kmz</a></h3>
    <p><img src="{% static "gewind_en/sample4.jpg" %}"></p>
    <br>
    <h3><a href="https://www.dropbox.com/s/6nbne6abz3wqmhw/sample5_en.kmz?dl=1">sample5_en.kmz</a>(*birdstrike prevention version)</h3>
    <p><img src="{% static "gewind_en/sample5.jpg" %}"></p>
{% endblock %}